name: _error
timestamp: 1509595436
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1509595363
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-1092: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-4120: Menu
  messages:
    system-messages-8179: 'System Messages'
  content:
    system-content-7974: 'Page Content'
  copyright:
    copyright-8238: Copyright
  spacer:
    spacer-1412: Spacer
  branding:
    branding-5217: Branding
  mobile-menu:
    mobile-menu-1209: Mobile-menu
inherit: {  }
