version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1509595363
layout:
  /header/:
    -
      - 'logo-1092 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-4120
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-8179
    -
      - system-content-7974
  /footer/:
    -
      - position-footer
    -
      - 'copyright-8238 40'
      - 'spacer-1412 30'
      - 'branding-5217 30'
  offcanvas:
    -
      - mobile-menu-1209
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
