version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1509595363
layout:
  /header/:
    -
      - 'logo-1280 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-5551
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-2504
    -
      - system-content-3158
  /footer/:
    -
      - position-footer
    -
      - 'copyright-5814 40'
      - 'spacer-9309 30'
      - 'branding-1199 30'
  offcanvas:
    -
      - mobile-menu-3102
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
