version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1509595363
layout:
  /header/:
    -
      - 'logo-5664 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-6506
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-5701
    -
      - system-content-9882
  /footer/:
    -
      - position-footer
    -
      - 'copyright-9726 40'
      - 'spacer-5968 30'
      - 'branding-2074 30'
  offcanvas:
    -
      - mobile-menu-9144
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
